/* ============================================================
   CUSTOMER SHOPPING BEHAVIOR ANALYSIS
   ------------------------------------------------------------
   Database   : customer_behavior (PostgreSQL)
   Table      : customer
   Source     : customer_shopping_behavior.csv (cleaned in Python,
                see customer_service.ipynb for the ETL steps)
   Author     : Ayush
   ------------------------------------------------------------
   This script contains all the exploratory and business
   questions answered for the Customer Shopping Behavior project.
   Queries are grouped by theme:
     1. Revenue Analysis
     2. Discounts & Promotions
     3. Product Performance
     4. Shipping Analysis
     5. Subscription Analysis
     6. Customer Segmentation
   ============================================================ */


-- ============================================================
-- 0. RAW DATA CHECK
-- ============================================================

-- Quick look at the full cleaned dataset
SELECT *
FROM customer;


-- ============================================================
-- 1. REVENUE ANALYSIS
-- ============================================================

-- Q1. What is the total revenue generated by each gender?
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2. Which age group generates the highest total revenue?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- ============================================================
-- 2. DISCOUNTS & PROMOTIONS
-- ============================================================

-- Q3. Which customers used a discount but still spent more than
--     the overall average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);


-- Q4. Which 5 products have the highest percentage of purchases
--     made with a discount applied?
SELECT
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- ============================================================
-- 3. PRODUCT PERFORMANCE
-- ============================================================

-- Q5. Which are the top 5 products with the highest average
--     review rating?
SELECT
    item_purchased,
    ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q6. What are the top 3 best-selling items within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- ============================================================
-- 4. SHIPPING ANALYSIS
-- ============================================================

-- Q7. How does the average purchase amount compare between
--     Standard and Express shipping?
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- ============================================================
-- 5. SUBSCRIPTION ANALYSIS
-- ============================================================

-- Q8. Do subscribed customers spend more? Compare average spend
--     and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q9. Among customers with more than 5 previous purchases (repeat
--     buyers), how are they split by subscription status?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- ============================================================
-- 6. CUSTOMER SEGMENTATION
-- ============================================================

-- Q10. Segment customers into New / Returning / Loyal based on
--      their number of previous purchases, and count each segment.
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
